export enum EmailType {
  SEVEN_DAY_REMINDER = 'SEVEN_DAY_REMINDER',
  THREE_DAY_REMINDER = 'THREE_DAY_REMINDER',
  ONE_DAY_REMINDER = 'ONE_DAY_REMINDER',
  SAME_DAY_REMINDER = 'SAME_DAY_REMINDER',
  OVERDUE_REMINDER = 'OVERDUE_REMINDER',
  CUSTOM_REMINDER = 'CUSTOM_REMINDER',
  PAYMENT_DUE_REMINDER = 'PAYMENT_DUE_REMINDER',
  FINAL_NOTICE = 'FINAL_NOTICE',
  TEST_SEVEN_DAY_REMINDER = 'TEST_SEVEN_DAY_REMINDER',
  TEST_THREE_DAY_REMINDER = 'TEST_THREE_DAY_REMINDER',
  TEST_ONE_DAY_REMINDER = 'TEST_ONE_DAY_REMINDER',
  TEST_SAME_DAY_REMINDER = 'TEST_SAME_DAY_REMINDER',
  TEST_OVERDUE_REMINDER = 'TEST_OVERDUE_REMINDER',
  TEST_CUSTOM_REMINDER = 'TEST_CUSTOM_REMINDER',
  TEST_PAYMENT_DUE_REMINDER = 'TEST_PAYMENT_DUE_REMINDER',
  TEST_FINAL_NOTICE = 'TEST_FINAL_NOTICE'
}

export const EMAIL_TYPE_LABELS: Record<EmailType, string> = {
  [EmailType.SEVEN_DAY_REMINDER]: '7-Day Reminder',
  [EmailType.THREE_DAY_REMINDER]: '3-Day Reminder',
  [EmailType.ONE_DAY_REMINDER]: '1-Day Reminder',
  [EmailType.SAME_DAY_REMINDER]: 'Same Day Reminder',
  [EmailType.OVERDUE_REMINDER]: 'Overdue Reminder',
  [EmailType.CUSTOM_REMINDER]: 'Custom Reminder',
  [EmailType.PAYMENT_DUE_REMINDER]: 'Payment Due Reminder',
  [EmailType.FINAL_NOTICE]: 'Final Notice',
  [EmailType.TEST_SEVEN_DAY_REMINDER]: 'Test 7-Day Reminder',
  [EmailType.TEST_THREE_DAY_REMINDER]: 'Test 3-Day Reminder',
  [EmailType.TEST_ONE_DAY_REMINDER]: 'Test 1-Day Reminder',
  [EmailType.TEST_SAME_DAY_REMINDER]: 'Test Same Day Reminder',
  [EmailType.TEST_OVERDUE_REMINDER]: 'Test Overdue Reminder',
  [EmailType.TEST_CUSTOM_REMINDER]: 'Test Custom Reminder',
  [EmailType.TEST_PAYMENT_DUE_REMINDER]: 'Test Payment Due Reminder',
  [EmailType.TEST_FINAL_NOTICE]: 'Test Final Notice'
};
