import api from "../axios";

export interface EvaluationV2Item {
  id: string;
  evaluationId: string;
  parameter: string;
  requiredValue: string;
  actualValue: string;
  source: string;
  status: "ELIGIBLE" | "NOT_ELIGIBLE";
  override: boolean;
  comments: string;
  brandEvaluationItemId: string;
  stage: "ONE" | "TWO" | "THREE" | "FOUR";
  brand_evaluation_items?: {
    id: string;
    parameter: string;
    requiredValue: string;
    sources: string[];
    stage: "ONE" | "TWO" | "THREE" | "FOUR";
    isActive: boolean;
    priority: number;
    description?: string;
  };
}

export interface EvaluationV2 {
  id: string;
  userId: string;
  loanId: string;
  createdAt: string;
  autoGeneratedFeedback?: string;
  isBsaReportAvailable: boolean;
  isCreditReportAvailable: boolean;
  isAaAvailable: boolean;
  is_cam_available: boolean;
  evaluation_item: EvaluationV2Item[];
  user?: {
    employment?: {
      salary?: number;
    }
  };
}

export const upsertEvaluateByLoanId = async (
  userId: string,
  brandId: string,
  loanId: string
): Promise<EvaluationV2> => {
  try {
    const response = await api.post(
      `/partner/brand/${brandId}/evaluation-v2/${userId}/${loanId}/upsert`
    );
    return response.data;
  } catch (error) {
    console.error("Error upserting evaluation V2:", error);
    throw error;
  }
};

export const getEvaluationByLoanId = async (
  userId: string,
  brandId: string,
  loanId: string
): Promise<EvaluationV2> => {
  try {
    const response = await api.get(
      `/partner/brand/${brandId}/evaluation-v2/${userId}/${loanId}`
    );
    return response.data;
  } catch (error) {
    console.error("Error fetching evaluation V2:", error);
    throw error;
  }
};

export const updateEvaluationV2Item = async (
  brandId: string,
  evaluationId: string,
  itemId: string,
  data: {
    actualValue?: string;
    status?: "ELIGIBLE" | "NOT_ELIGIBLE";
    override?: boolean;
    comments?: string;
  }
): Promise<EvaluationV2Item> => {
  try {
    const response = await api.put(
      `/partner/brand/${brandId}/evaluation-v2/${evaluationId}/item/${itemId}`,
      data
    );
    return response.data;
  } catch (error) {
    console.error("Error updating evaluation V2 item:", error);
    throw error;
  }
};
