export enum EmailType {
  SEVEN_DAY_REMINDER = 'SEVEN_DAY_REMINDER',
  THREE_DAY_REMINDER = 'THREE_DAY_REMINDER',
  ONE_DAY_REMINDER = 'ONE_DAY_REMINDER',
  SAME_DAY_REMINDER = 'SAME_DAY_REMINDER',
  OVERDUE_REMINDER = 'OVERDUE_REMINDER',
  CUSTOM_REMINDER = 'CUSTOM_REMINDER',
  PAYMENT_DUE_REMINDER = 'PAYMENT_DUE_REMINDER',
  FINAL_NOTICE = 'FINAL_NOTICE',
  TEST_SEVEN_DAY_REMINDER = 'TEST_SEVEN_DAY_REMINDER',
  TEST_THREE_DAY_REMINDER = 'TEST_THREE_DAY_REMINDER',
  TEST_ONE_DAY_REMINDER = 'TEST_ONE_DAY_REMINDER',
  TEST_SAME_DAY_REMINDER = 'TEST_SAME_DAY_REMINDER',
  TEST_OVERDUE_REMINDER = 'TEST_OVERDUE_REMINDER',
  TEST_CUSTOM_REMINDER = 'TEST_CUSTOM_REMINDER',
  TEST_PAYMENT_DUE_REMINDER = 'TEST_PAYMENT_DUE_REMINDER',
  TEST_FINAL_NOTICE = 'TEST_FINAL_NOTICE'
}
